Repository MTES-MCT/zero-logement-vacant, pull requests merged in 2022-12, with the labels that each got.

#169 Fix coordinates inversion on filter with geo perimeter
  server/repositories/housingRepository.ts
Labels: bug

#172 Upgrade to node 16
  .github/workflows/github-actions.yml
  frontend/cypress.config.ts
  frontend/cypress/e2e/visual-regression-testing.cy.ts
  frontend/cypress/snapshots/accessibilite.snap.png
  frontend/cypress/snapshots/accueil.snap.png
  frontend/cypress/snapshots/base-de-donnees.snap.png
  frontend/cypress/snapshots/campagnes.snap.png
  frontend/cypress/snapshots/compte/mot-de-passe.snap.png
  frontend/cypress/snapshots/landing.snap.png
  frontend/cypress/snapshots/perimetres.snap.png
  frontend/cypress/snapshots/ressources.snap.png
  frontend/cypress/snapshots/stats.snap.png
  frontend/cypress/snapshots/suivi/etablissement/id.snap.png
  frontend/cypress/support/commands.ts
  frontend/cypress/support/e2e.ts
  frontend/cypress/tsconfig.json
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
Labels: dependencies

#162 Rework owner page
  database/migrations/046-add-event-title.ts
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.scss
  frontend/src/colors.scss
  frontend/src/components/AppMultiSelect/AppMultiSelect.tsx
  frontend/src/components/OwnerCard/OwnerCard.tsx
  frontend/src/components/OwnerCard/owner-card.module.scss
  frontend/src/components/OwnerDetailsCard/OwnerDetailsCard.tsx
  frontend/src/components/OwnerDetailsCard/owner-details-card.module.scss
  frontend/src/components/OwnerHousingCard/OwnerHousingCard.tsx
  frontend/src/components/OwnerHousingCard/owner-housing-card.module.scss
  frontend/src/components/modals/HousingNoteModal/HousingNoteModal.tsx
  frontend/src/dsfr-fix.scss
  frontend/src/hooks/useForm.tsx
  frontend/src/hooks/useOwner.tsx
  frontend/src/models/ContactKind.tsx
  frontend/src/models/Event.tsx
  frontend/src/models/HousingFilters.tsx
  frontend/src/models/Note.tsx
  frontend/src/models/SelectOption.tsx
  frontend/src/services/event.service.ts
  frontend/src/store/actions/housingAction.tsx
  frontend/src/store/actions/ownerAction.tsx
  frontend/src/views/Owner/OwnerView.test.tsx
  frontend/src/views/Owner/OwnerView.tsx
  frontend/src/views/Owner/owner.module.scss
  package-lock.json
  package.json
  server/controllers/accountController.test.ts
  server/controllers/campaignController.test.ts
  server/controllers/establishmentController.test.ts
  server/controllers/eventController.test.ts
  server/controllers/eventController.ts
  server/controllers/geoController.test.ts
  server/controllers/housingController.test.ts
  server/controllers/ownerController.ts
  server/errors/housingMissingError.ts
  server/errors/ownerMissingError.ts
  server/models/EventApi.ts
  server/repositories/eventRepository.ts
  server/repositories/ownerRepository.ts
  server/routers/protected.ts
  server/routers/unprotected.ts
  server/server.ts
  server/test/testFixtures.ts
  shared/models/EventDTO.ts
  tsconfig.json
  types/express-jwt/index.d.ts
Labels: enhancement

#182 Fix issues on campaigns
  frontend/src/components/CampaignBundleList/CampaignBundleList.tsx
  frontend/src/hooks/useCampaignBundleList.tsx
  frontend/src/hooks/useForm.tsx
  frontend/src/models/Campaign.tsx
  frontend/src/utils/dateUtils.ts
  frontend/src/views/Campaign/CampaignToValidate.tsx
  frontend/src/views/Dashboard/DashboardView.tsx
Labels: bug

#181 Fix monitoring issues
  server/repositories/establishmentRepository.ts
  server/repositories/housingRepository.ts
Labels: bug

#171 Upgrade testing library and react types to react 18
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/modals/CampaignCreationModal/CampaignCreationModal.test.tsx
  frontend/src/components/modals/CampaignCreationModal/CampaignCreationModal.tsx
  frontend/src/index.tsx
  frontend/src/views/Login/LoginView.test.tsx
  package-lock.json
  package.json
  server/errors/routeNotFoundError.ts
  server/middlewares/error-handler.ts
  server/server.ts
  server/test/setupTests.ts
Labels: dependencies
