Repository MTES-MCT/zero-logement-vacant, pull requests merged in 2025-09, with the labels that each got.

#1373 Update perimeters modal size to extra-extra-large
  frontend/src/components/modals/GeoPerimetersModal/PerimetersModal.tsx
Labels: enhancement

#1382 Replace deprecated vitest workspaces by a root project config
  vitest.config.ts
  vitest.workspace.ts
Labels: tests

#1348 Add alert roles
  frontend/src/components/SelectableListHeader/SelectableListHeader.tsx
  frontend/src/views/HousingList/HousingListView.tsx
Labels: stand by, accessibility

#1396 fix(tests): resolve vitest compatibility issues
  server/src/repositories/test/housingRepository.test.ts
  server/src/test/testFixtures.ts
  server/src/utils/addressNormalization.test.ts
  server/src/utils/addressNormalization.ts
Labels: tests
