Repository MTES-MCT/zero-logement-vacant, pull requests merged in 2025-08, with the labels that each got.

#1329 Use perimeter.kind in the perimeter filter
  frontend/src/components/HousingListFilters/HousingListFiltersSidemenu.tsx
  frontend/src/components/HousingListFilters/PerimeterSearchableSelect.tsx
Labels: bug

#1330 Check establishment geocodes before adding a housing
  server/src/controllers/housingController.ts
Labels: bug

#1334 Update button text for housing edit action
  frontend/src/components/HousingList/HousingList.tsx
Labels: enhancement

#1324 fix: optimize Puppeteer PDF generation to prevent DOM timeouts
  nx.json
  package.json
  packages/draft/package.json
  packages/draft/project.json
  packages/draft/src/pdf.ts
  server/package.json
  yarn.lock
Labels: bug, enhancement

#1346 Fix housing export
  packages/api-sdk/src/campaign-api.ts
  queue/src/workers/generate-mails.ts
  server/src/controllers/housingController.ts
  server/src/controllers/housingExportController.ts
  server/src/infra/config.ts
  server/src/repositories/housingRepository.ts
  server/src/repositories/ownerRepository.ts
  server/src/repositories/test/ownerRepository.test.ts
  server/src/utils/excelUtils.ts
Labels: bug

#1355 Set the housing table width to 100%
  frontend/src/components/AdvancedTable/AdvancedTable.tsx
  frontend/src/components/Campaign/CampaignRecipients.tsx
  frontend/src/components/HousingList/HousingList.tsx
Labels: bug

#1358 Improve GroupCard and HousingCount accessibility
  frontend/package.json
  frontend/src/components/GroupCard/GroupCard.tsx
  frontend/src/components/HousingCount/HousingCount.tsx
  yarn.lock
Labels: accessibility

#1352 Add posthog’s people
  frontend/src/components/Auth/RequireAuth.tsx
  frontend/src/views/Account/AccountSideMenu.tsx
Labels: enhancement
